apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: in28min
  name: in28min
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 15
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: in28min
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: in28min
    spec:
      containers:
        - image: in28min/hello-world-nodejs:0.0.2.RELEASE
          imagePullPolicy: IfNotPresent
          name: hello-world-rest-api
          env:
            - name: app_url
              valueFrom:
                configMapKeyRef:
                  name: in28min-configmap
                  key: app_url
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
