
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: in28min
  name: in28min
  namespace: default  
spec:
  replicas: 3
  minReadySeconds: 45
  selector:
    matchLabels:
      app: in28min
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        app: in28min
    spec:
      containers:
      - image: in28min/hello-world-nodejs:0.0.2.RELEASE
        imagePullPolicy: IfNotPresent
        name: hello-world-rest-api
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

# if the pods are already there then it won't change anything until 
# the pods are terminated (manually or because of errors)
# after the $kubectl apply -f replicaset.yml the new pods will be created with current configs

#better will be if we use deployment and not ReplicaSet
