apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "5"
    creationTimestamp: "2023-01-04T09:49:08Z"
    generation: 10
    labels:
      app: in28min
    name: in28min
    namespace: default
    resourceVersion: "94436"
    uid: c258a19f-58bd-494e-a459-9daefaf4978d
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: in28min
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: in28min
      spec:
        containers:
        - image: in28min/hello-world-nodejs:0.0.2.RELEASE
          imagePullPolicy: IfNotPresent
          name: hello-world-rest-api
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    conditions:
    - lastTransitionTime: "2023-01-04T11:31:36Z"
      lastUpdateTime: "2023-01-04T11:31:36Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-01-04T09:49:08Z"
      lastUpdateTime: "2023-01-04T12:16:56Z"
      message: ReplicaSet "in28min-7488fc7f64" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 10
    readyReplicas: 3
    replicas: 3
    updatedReplicas: 3
kind: List
metadata:
  resourceVersion: ""
